name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Thay 'master' bằng tên nhánh của bạn nếu cần

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Hoặc phiên bản Node.js mà bạn đang sử dụng

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # Nhánh đích để triển khai
          folder: dist/pwa # Thư mục chứa các tệp tin đã build
